# -*- mode: Makefile -*-

# -----------------------------------
# ROOT: Required. Set ROOTSYS else set it here
ROOTDIR = `root-config --prefix`
ifneq (${ROOTSYS},)
	ROOTSYS = ${ROOTDIR}
endif

# -----------------------------------
# COMPILER SETTINGS
CC = g++
