# -*- mode: Makefile -*-

# -----------------------------------
# BASEDIR is the location of the package. 
# if not defined, assumed to be PWD
BASEDIR = 

# -----------------------------------
# ROOT: Required. Set ROOTSYS else set it here
ROOTDIR = /Users/twongjirad/software/root_v5.34.14
ifneq (${ROOTSYS},)
	ROOTSYS = ${ROOTDIR}
endif

# -----------------------------------
# Prob3++
PROBTPP_DIR = /Users/twongjirad/working/sk/Prob3++
PROBTPP_LIB = /Users/twongjirad/working/sk/Prob3++/libThreeProb_2.11.a

# -----------------------------------
# T2K REWIGHT
# SUPPORTED VERSIONS: 0, v1r17
# 0 means that T2KREWEIGHT NOT used
T2KRW_VER = 0
# Location of T2KRewight
T2KREWEIGHT_DIR = 
# NEUT_ROOT

# -----------------------------------
# Google Performance Tools
# Used to trace the program
# If installed and want to be used
# Of course, as with all profiling tools, there will be a cost in performance if activated
USE_GPERFTOOLS = 0

# -----------------------------------
# Python Tools
# Cython support available
BUILD_CYTHON_LIBRARIES = 0
PYTHONINC = /usr/local/python-2.7/include/python2.7
PYTHONLIB = -L/usr/local/python-2.7/lib -lpython2.7

# -----------------------------------
# COMPILER SETTINGS
CC = c++