# -*- mode: Makefile -*-
include ../Makefile.config

LIBNAME = analysisfw

BASEDIR = ..
DEPDIR = .dep
OBJDIR = .obj

LOCAL_INC += -I./include

CCSRCS = $(wildcard src/*.cc)
VPATH += 

include ../Makefile.auto

